<?php

namespace ContainerTf1uaTo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccountTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AccountType' shared autowired service.
     *
     * @return \App\Form\AccountType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AccountType.php';

        return $container->privates['App\\Form\\AccountType'] = new \App\Form\AccountType();
    }
}
