<?php

namespace Container67ee2ux;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_As8fOldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.As8fOld' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.As8fOld'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ar' => ['privates', 'App\\Repository\\AccountRepository', 'getAccountRepositoryService', true],
        ], [
            'ar' => 'App\\Repository\\AccountRepository',
        ]);
    }
}
