<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container67ee2ux\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container67ee2ux/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container67ee2ux.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container67ee2ux\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container67ee2ux\App_KernelDevDebugContainer([
    'container.build_hash' => '67ee2ux',
    'container.build_id' => '369fec46',
    'container.build_time' => 1682280540,
], __DIR__.\DIRECTORY_SEPARATOR.'Container67ee2ux');
