<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTf1uaTo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTf1uaTo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTf1uaTo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTf1uaTo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTf1uaTo\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tf1uaTo',
    'container.build_id' => '08c8f144',
    'container.build_time' => 1682443620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTf1uaTo');
